---
- name: Install nvm
  become_user: "{{user_remote}}"
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{home_folder}}/.nvm/nvm.sh"
