---
- name: Configurations to "remote" host
  hosts: local
  remote_user: "{{user_remote}}"
  become: yes
  pre_tasks:
    - name: update
      raw: sudo apt-get -y update
  tasks:
    - name: setup git
      include_role:
        name: git

    - name: Install packages
      include_role:
        name: install_packages

    - name: Install NVM
      include_role:
        name: nvm

    - name: Install Oh My ZSH
      include_role:
        name: oh_my_zsh     

    - name: Install Pyenv
      include_role:
        name: pyenv
