---
- name: Configurations to "remote" host
  hosts: local
  remote_user: "{{user_remote}}"
  become: yes

  pre_tasks:
    - name: Install curl package
      apt:
        name: curl
        state: present
  
    - name: Enable Microsoft Package Repo - Part 1
      raw: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    
    - name: Enable Microsoft Package Repo - Part 2
      raw:  sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
    
    - name: Enable Microsoft Package Repo - Part 3
      raw: sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
 
    - name: Enable Microsoft Package Repo - Part 3
      raw: sudo apt install apt-transport-https

    - name: Update System Packages
      raw: sudo apt update

  tasks:
    - name: Install packages
      include_role:
        name: install_packages

    - name: config meld
      include_role:
        name: meld

    - name: setup git
      include_role:
        name: git

    - name: Install Oh My ZSH
      include_role:
        name: oh_my_zsh     

    - name: Install NVM
      include_role:
        name: nvm

    - name: Install Pyenv
      include_role:
        name: pyenv
