---
- name: Configurations to "remote" host
  hosts: local
  remote_user: "{{user_remote}}"
  become: yes
  pre_tasks:
    - name: update
      raw: sudo pacman -Syyu "{{ not_confirm }}"

  tasks:
    - name: Setup Git
      import_role:
        name: git
      become: yes

    - name: Remove unsued packages
      import_role:
        name: uninstall_packages
      become: yes

    - name: Install packages
      import_role:
        name: install_packages
      become: yes