---
- name: Create directory Fonts
  file:
    path: "{{home_folder}}/.local/share/fonts"
    state: directory
    recurse: yes
    mode: '777'

- name: Install Fonts
  shell: cd {{home_folder}}/.local/share/fonts && curl -fLo "Droid Sans Mono for Powerline Nerd Font Complete.otf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf