---
- name: Backing up existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc ~/.zshrc.orig; fi
  become_user: "{{user_remote}}"

- name: Cloning  oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{name_folder_dest_zsh}}"

- name: Creating new ~/.zshrc
  copy:
    src: "{{name_folder_dest_zsh}}/templates/zshrc.zsh-template"
    dest: "{{home_folder}}/.zshrc"
  become_user: "{{user_remote}}"