--- 
- 
  git_config: 
    name: user.email
    value: "{{git_email}}"
  name: "Config email git"
- 
  git_config: 
    name: user.name
    value: "{{git_name}}"
  name: "Config name git"
- 
  become: false
  name: "Set cache password git"
  shell: "git config --global credential.helper 'cache --timeout=360000'"