---
- name: Config email git
  git_config:
    name: user.email
    value: "{{git_email}}"

- name: Config name git
  git_config:
    name: user.name
    value: "{{git_name}}"

- name: Set cache password git
  shell: git config --global credential.helper 'cache --timeout=360000'
  become: no
