---
- name: "Create symlink snap to /var/lib/snapd/snap"
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    state: link
    force: yes
  become: yes

- name: Restart snapd
  command: systemctl restart snapd

- name: Default staet
  command: systemctl enable --now snapd.socket
