---
- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{home_folder}}/.pyenv"

- name: Adds permission to the pyenv directory
  file:
    path: "{{home_folder}}/.pyenv"
    mode: '777'

- name: Install pyenv-virtualenv plugin
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{home_folder}}/.pyenv/plugins/pyenv-virtualenv"
